### ISSUE TITLE
Why need mnemonic for monitoring?

### ISSUE THREAD

**Issue by Drjacky** [OpenSea-Sniper/OpenSea-Python-Bot#2]
Why do we need to pass the mnemonic parameter for monitoring mode?!

**Comment by OpenSea-Sniper** [comment]
It’s basically only used when a buy needs to be triggered if you get a super low entry. Mnemonic isn’t used for the monitoring aspect but only for buy aspect. Maybe I’ll try to refactor the code to make it better in next version

**Comment by ism** [comment]
This is needed because mnemonic is being sent to discord. Please report
